apiVersion: operators.coreos.com/v1alpha2
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "keycloak.japannext.co.jp/v1alpha2",
          "kind": "KeycloakEndpoint",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "keycloak-operator",
              "app.kubernetes.io/instance": "keycloakendpoint-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "keycloakendpoint",
              "app.kubernetes.io/part-of": "keycloak-operator"
            },
            "name": "keycloakendpoint-sample"
          },
          "spec": null
        },
        {
          "apiVersion": "keycloak.japannext.co.jp/v1alpha2",
          "kind": "KeycloakRealm",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "keycloak-operator",
              "app.kubernetes.io/instance": "keycloakrealm-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "keycloakrealm",
              "app.kubernetes.io/part-of": "keycloak-operator"
            },
            "name": "keycloakrealm-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2023-08-25T00:25:28Z"
    operators.operatorframework.io/builder: operator-sdk-v1.31.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: keycloak-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: KeycloakEndpoint is the Schema for the keycloakendpoints API
      displayName: Keycloak Endpoint
      kind: KeycloakEndpoint
      name: keycloakendpoints.keycloak.japannext.co.jp
      version: v1alpha2
    - description: KeycloakRealm is the Schema for the keycloakrealms API
      displayName: Keycloak Realm
      kind: KeycloakRealm
      name: keycloakrealms.keycloak.japannext.co.jp
      version: v1alpha2
  description: Manage keycloak API
  displayName: Keycloak operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - keycloak.japannext.co.jp
          resources:
          - keycloakendpoints
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - keycloak.japannext.co.jp
          resources:
          - keycloakendpoints/finalizers
          verbs:
          - update
        - apiGroups:
          - keycloak.japannext.co.jp
          resources:
          - keycloakendpoints/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - keycloak.japannext.co.jp
          resources:
          - keycloakrealms
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - keycloak.japannext.co.jp
          resources:
          - keycloakrealms/finalizers
          verbs:
          - update
        - apiGroups:
          - keycloak.japannext.co.jp
          resources:
          - keycloakrealms/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: keycloak-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: keycloak-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: keycloak-operator
          control-plane: controller-manager
        name: keycloak-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: controller:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: keycloak-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: keycloak-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - keycloak
  links:
  - name: Keycloak Operator
    url: https://keycloak-operator.domain
  maturity: alpha
  provider:
    name: Japannext
    url: https://github.com/japannext/keycloak-operator
  version: 0.0.1
