---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-keycloak-japannext-co-jp-v1alpha2-keycloakrealm
  failurePolicy: Fail
  name: mkeycloakrealm.kb.io
  rules:
  - apiGroups:
    - keycloak.japannext.co.jp
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - keycloakrealms
  sideEffects: None
