# permissions for end users to edit keycloakclusterendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: keycloakclusterendpoint-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: keycloak-operator
    app.kubernetes.io/part-of: keycloak-operator
    app.kubernetes.io/managed-by: kustomize
  name: keycloakclusterendpoint-editor-role
rules:
- apiGroups:
  - keycloak.japannext.co.jp
  resources:
  - keycloakclusterendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.japannext.co.jp
  resources:
  - keycloakclusterendpoints/status
  verbs:
  - get
