# permissions for end users to view keycloakendpoints.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: keycloakendpoint-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: keycloak-operator
    app.kubernetes.io/part-of: keycloak-operator
    app.kubernetes.io/managed-by: kustomize
  name: keycloakendpoint-viewer-role
rules:
- apiGroups:
  - keycloak.japannext.co.jp
  resources:
  - keycloakendpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keycloak.japannext.co.jp
  resources:
  - keycloakendpoints/status
  verbs:
  - get
