# permissions for end users to view keycloakrealmroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: keycloakrealmrole-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: keycloak-operator
    app.kubernetes.io/part-of: keycloak-operator
    app.kubernetes.io/managed-by: kustomize
  name: keycloakrealmrole-viewer-role
rules:
- apiGroups:
  - keycloak.japannext.co.jp
  resources:
  - keycloakrealmroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keycloak.japannext.co.jp
  resources:
  - keycloakrealmroles/status
  verbs:
  - get
