apiVersion: operators.coreos.com/v1alpha2
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: keycloak-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: KeycloakEndpoint is the Schema for the keycloakendpoints API
      displayName: Keycloak Endpoint
      kind: KeycloakEndpoint
      name: keycloakendpoints.keycloak.japannext.co.jp
      version: v1alpha2
    - description: KeycloakRealm is the Schema for the keycloakrealms API
      displayName: Keycloak Realm
      kind: KeycloakRealm
      name: keycloakrealms.keycloak.japannext.co.jp
      version: v1alpha2
  description: Manage keycloak API
  displayName: Keycloak operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - keycloak
  links:
  - name: Keycloak Operator
    url: https://keycloak-operator.domain
  maturity: alpha
  provider:
    name: Japannext
    url: https://github.com/japannext/keycloak-operator
  version: 0.0.0
