apiVersion: keycloak.japannext.co.jp/v1alpha2
kind: KeycloakLDAPSync
metadata:
  labels:
    app.kubernetes.io/name: keycloakldapsync
    app.kubernetes.io/instance: keycloakldapsync-sample
    app.kubernetes.io/part-of: keycloak-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: keycloak-operator
  name: keycloakldapsync-sample
spec:
  # TODO(user): Add fields here
