# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/keycloak.japannext.co.jp_keycloakclientrolemappings.yaml
- bases/keycloak.japannext.co.jp_keycloakclientroles.yaml
- bases/keycloak.japannext.co.jp_keycloakclients.yaml
- bases/keycloak.japannext.co.jp_keycloakclientscopeprotocolmappers.yaml
- bases/keycloak.japannext.co.jp_keycloakclientscopes.yaml
- bases/keycloak.japannext.co.jp_keycloakclusterendpoints.yaml
- bases/keycloak.japannext.co.jp_keycloakendpoints.yaml
- bases/keycloak.japannext.co.jp_keycloakldapfederations.yaml
- bases/keycloak.japannext.co.jp_keycloakldapmappers.yaml
- bases/keycloak.japannext.co.jp_keycloakldapsyncs.yaml
- bases/keycloak.japannext.co.jp_keycloakrealms.yaml
- bases/keycloak.japannext.co.jp_keycloakclientprotocolmappers.yaml
- bases/keycloak.japannext.co.jp_keycloakrealmroles.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- patches/webhook_in_keycloakrealms.yaml
- patches/webhook_in_keycloakendpoints.yaml
- patches/webhook_in_keycloakclusterendpoints.yaml
#- patches/webhook_in_keycloakclients.yaml
#- patches/webhook_in_keycloakclientroles.yaml
#- patches/webhook_in_keycloakclientrolemappings.yaml
#- patches/webhook_in_keycloakldapfederations.yaml
#- patches/webhook_in_keycloakendpoints.yaml
#- patches/webhook_in_keycloakclusterendpoints.yaml
#- patches/webhook_in_keycloakrealms.yaml
#- patches/webhook_in_keycloakldapsyncs.yaml
#- patches/webhook_in_keycloakldapmappers.yaml
#- patches/webhook_in_keycloakclientscopeprotocolmappers.yaml
#- patches/webhook_in_keycloakclientscopes.yaml
#- patches/webhook_in_keycloakclientprotocolmappers.yaml
#- patches/webhook_in_keycloakrealmroles.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_keycloakrealms.yaml
- patches/cainjection_in_keycloakendpoints.yaml
- patches/cainjection_in_keycloakclusterendpoints.yaml
#- patches/cainjection_in_keycloakclients.yaml
#- patches/cainjection_in_keycloakclientroles.yaml
#- patches/cainjection_in_keycloakclientrolemappings.yaml
#- patches/cainjection_in_keycloakldapfederations.yaml
#- patches/cainjection_in_keycloakendpoints.yaml
#- patches/cainjection_in_keycloakclusterendpoints.yaml
#- patches/cainjection_in_keycloakrealms.yaml
#- patches/cainjection_in_keycloakldapsyncs.yaml
#- patches/cainjection_in_keycloakldapmappers.yaml
#- patches/cainjection_in_keycloakclientscopeprotocolmappers.yaml
#- patches/cainjection_in_keycloakclientscopes.yaml
#- patches/cainjection_in_keycloakclientprotocolmappers.yaml
#- patches/cainjection_in_keycloakrealmroles.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
