apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-manager-role
  labels:
  {{- include "keycloak-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keycloak.japannext.co.jp
  resources:
  - keycloakclusterendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.japannext.co.jp
  resources:
  - keycloakclusterendpoints/finalizers
  verbs:
  - update
- apiGroups:
  - keycloak.japannext.co.jp
  resources:
  - keycloakclusterendpoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - keycloak.japannext.co.jp
  resources:
  - keycloakendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.japannext.co.jp
  resources:
  - keycloakendpoints/finalizers
  verbs:
  - update
- apiGroups:
  - keycloak.japannext.co.jp
  resources:
  - keycloakendpoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - keycloak.japannext.co.jp
  resources:
  - keycloakrealms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.japannext.co.jp
  resources:
  - keycloakrealms/finalizers
  verbs:
  - update
- apiGroups:
  - keycloak.japannext.co.jp
  resources:
  - keycloakrealms/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "keycloak-operator.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: keycloak-operator
    app.kubernetes.io/part-of: keycloak-operator
  {{- include "keycloak-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "keycloak-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "keycloak-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'