//go:build !ignore_autogenerated

/*
Copyright 2024 Japannext.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"github.com/japannext/keycloak-operator/gocloak"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiStatus) DeepCopyInto(out *ApiStatus) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiStatus.
func (in *ApiStatus) DeepCopy() *ApiStatus {
	if in == nil {
		return nil
	}
	out := new(ApiStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicAuthSecret) DeepCopyInto(out *BasicAuthSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicAuthSecret.
func (in *BasicAuthSecret) DeepCopy() *BasicAuthSecret {
	if in == nil {
		return nil
	}
	out := new(BasicAuthSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateLdapMapper) DeepCopyInto(out *CertificateLdapMapper) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateLdapMapper.
func (in *CertificateLdapMapper) DeepCopy() *CertificateLdapMapper {
	if in == nil {
		return nil
	}
	out := new(CertificateLdapMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapValue) DeepCopyInto(out *ConfigMapValue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapValue.
func (in *ConfigMapValue) DeepCopy() *ConfigMapValue {
	if in == nil {
		return nil
	}
	out := new(ConfigMapValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointSelector) DeepCopyInto(out *EndpointSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointSelector.
func (in *EndpointSelector) DeepCopy() *EndpointSelector {
	if in == nil {
		return nil
	}
	out := new(EndpointSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FullNameLdapMapper) DeepCopyInto(out *FullNameLdapMapper) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FullNameLdapMapper.
func (in *FullNameLdapMapper) DeepCopy() *FullNameLdapMapper {
	if in == nil {
		return nil
	}
	out := new(FullNameLdapMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupLdapMapper) DeepCopyInto(out *GroupLdapMapper) {
	*out = *in
	if in.GroupObjectClasses != nil {
		in, out := &in.GroupObjectClasses, &out.GroupObjectClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupLdapMapper.
func (in *GroupLdapMapper) DeepCopy() *GroupLdapMapper {
	if in == nil {
		return nil
	}
	out := new(GroupLdapMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupRepresentation) DeepCopyInto(out *GroupRepresentation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupRepresentation.
func (in *GroupRepresentation) DeepCopy() *GroupRepresentation {
	if in == nil {
		return nil
	}
	out := new(GroupRepresentation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardcodedAttributeMapper) DeepCopyInto(out *HardcodedAttributeMapper) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardcodedAttributeMapper.
func (in *HardcodedAttributeMapper) DeepCopy() *HardcodedAttributeMapper {
	if in == nil {
		return nil
	}
	out := new(HardcodedAttributeMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardcodedLdapAttributeMapper) DeepCopyInto(out *HardcodedLdapAttributeMapper) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardcodedLdapAttributeMapper.
func (in *HardcodedLdapAttributeMapper) DeepCopy() *HardcodedLdapAttributeMapper {
	if in == nil {
		return nil
	}
	out := new(HardcodedLdapAttributeMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardcodedLdapGroupMapper) DeepCopyInto(out *HardcodedLdapGroupMapper) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardcodedLdapGroupMapper.
func (in *HardcodedLdapGroupMapper) DeepCopy() *HardcodedLdapGroupMapper {
	if in == nil {
		return nil
	}
	out := new(HardcodedLdapGroupMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardcodedLdapRoleMapper) DeepCopyInto(out *HardcodedLdapRoleMapper) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardcodedLdapRoleMapper.
func (in *HardcodedLdapRoleMapper) DeepCopy() *HardcodedLdapRoleMapper {
	if in == nil {
		return nil
	}
	out := new(HardcodedLdapRoleMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClient) DeepCopyInto(out *KeycloakClient) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClient.
func (in *KeycloakClient) DeepCopy() *KeycloakClient {
	if in == nil {
		return nil
	}
	out := new(KeycloakClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakClient) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientList) DeepCopyInto(out *KeycloakClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientList.
func (in *KeycloakClientList) DeepCopy() *KeycloakClientList {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientProtocolMapper) DeepCopyInto(out *KeycloakClientProtocolMapper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientProtocolMapper.
func (in *KeycloakClientProtocolMapper) DeepCopy() *KeycloakClientProtocolMapper {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientProtocolMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakClientProtocolMapper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientProtocolMapperList) DeepCopyInto(out *KeycloakClientProtocolMapperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakClientProtocolMapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientProtocolMapperList.
func (in *KeycloakClientProtocolMapperList) DeepCopy() *KeycloakClientProtocolMapperList {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientProtocolMapperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakClientProtocolMapperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientProtocolMapperSpec) DeepCopyInto(out *KeycloakClientProtocolMapperSpec) {
	*out = *in
	out.Endpoint = in.Endpoint
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientProtocolMapperSpec.
func (in *KeycloakClientProtocolMapperSpec) DeepCopy() *KeycloakClientProtocolMapperSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientProtocolMapperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientProtocolMapperStatus) DeepCopyInto(out *KeycloakClientProtocolMapperStatus) {
	*out = *in
	in.Api.DeepCopyInto(&out.Api)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientProtocolMapperStatus.
func (in *KeycloakClientProtocolMapperStatus) DeepCopy() *KeycloakClientProtocolMapperStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientProtocolMapperStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientRole) DeepCopyInto(out *KeycloakClientRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientRole.
func (in *KeycloakClientRole) DeepCopy() *KeycloakClientRole {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakClientRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientRoleList) DeepCopyInto(out *KeycloakClientRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakClientRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientRoleList.
func (in *KeycloakClientRoleList) DeepCopy() *KeycloakClientRoleList {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakClientRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientRoleMapping) DeepCopyInto(out *KeycloakClientRoleMapping) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientRoleMapping.
func (in *KeycloakClientRoleMapping) DeepCopy() *KeycloakClientRoleMapping {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientRoleMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakClientRoleMapping) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientRoleMappingList) DeepCopyInto(out *KeycloakClientRoleMappingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakClientRoleMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientRoleMappingList.
func (in *KeycloakClientRoleMappingList) DeepCopy() *KeycloakClientRoleMappingList {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientRoleMappingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakClientRoleMappingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientRoleMappingSpec) DeepCopyInto(out *KeycloakClientRoleMappingSpec) {
	*out = *in
	out.Endpoint = in.Endpoint
	out.Subject = in.Subject
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientRoleMappingSpec.
func (in *KeycloakClientRoleMappingSpec) DeepCopy() *KeycloakClientRoleMappingSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientRoleMappingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientRoleMappingStatus) DeepCopyInto(out *KeycloakClientRoleMappingStatus) {
	*out = *in
	in.Api.DeepCopyInto(&out.Api)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientRoleMappingStatus.
func (in *KeycloakClientRoleMappingStatus) DeepCopy() *KeycloakClientRoleMappingStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientRoleMappingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientRoleSpec) DeepCopyInto(out *KeycloakClientRoleSpec) {
	*out = *in
	out.Endpoint = in.Endpoint
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientRoleSpec.
func (in *KeycloakClientRoleSpec) DeepCopy() *KeycloakClientRoleSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientRoleStatus) DeepCopyInto(out *KeycloakClientRoleStatus) {
	*out = *in
	in.Api.DeepCopyInto(&out.Api)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientRoleStatus.
func (in *KeycloakClientRoleStatus) DeepCopy() *KeycloakClientRoleStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientScope) DeepCopyInto(out *KeycloakClientScope) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientScope.
func (in *KeycloakClientScope) DeepCopy() *KeycloakClientScope {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakClientScope) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientScopeList) DeepCopyInto(out *KeycloakClientScopeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakClientScope, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientScopeList.
func (in *KeycloakClientScopeList) DeepCopy() *KeycloakClientScopeList {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientScopeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakClientScopeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientScopeProtocolMapper) DeepCopyInto(out *KeycloakClientScopeProtocolMapper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientScopeProtocolMapper.
func (in *KeycloakClientScopeProtocolMapper) DeepCopy() *KeycloakClientScopeProtocolMapper {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientScopeProtocolMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakClientScopeProtocolMapper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientScopeProtocolMapperList) DeepCopyInto(out *KeycloakClientScopeProtocolMapperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakClientScopeProtocolMapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientScopeProtocolMapperList.
func (in *KeycloakClientScopeProtocolMapperList) DeepCopy() *KeycloakClientScopeProtocolMapperList {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientScopeProtocolMapperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakClientScopeProtocolMapperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientScopeProtocolMapperSpec) DeepCopyInto(out *KeycloakClientScopeProtocolMapperSpec) {
	*out = *in
	out.Endpoint = in.Endpoint
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientScopeProtocolMapperSpec.
func (in *KeycloakClientScopeProtocolMapperSpec) DeepCopy() *KeycloakClientScopeProtocolMapperSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientScopeProtocolMapperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientScopeProtocolMapperStatus) DeepCopyInto(out *KeycloakClientScopeProtocolMapperStatus) {
	*out = *in
	in.Api.DeepCopyInto(&out.Api)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientScopeProtocolMapperStatus.
func (in *KeycloakClientScopeProtocolMapperStatus) DeepCopy() *KeycloakClientScopeProtocolMapperStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientScopeProtocolMapperStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientScopeSpec) DeepCopyInto(out *KeycloakClientScopeSpec) {
	*out = *in
	out.Endpoint = in.Endpoint
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientScopeSpec.
func (in *KeycloakClientScopeSpec) DeepCopy() *KeycloakClientScopeSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientScopeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientScopeStatus) DeepCopyInto(out *KeycloakClientScopeStatus) {
	*out = *in
	in.Api.DeepCopyInto(&out.Api)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientScopeStatus.
func (in *KeycloakClientScopeStatus) DeepCopy() *KeycloakClientScopeStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientScopeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientSpec) DeepCopyInto(out *KeycloakClientSpec) {
	*out = *in
	out.Endpoint = in.Endpoint
	out.Secret = in.Secret
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientSpec.
func (in *KeycloakClientSpec) DeepCopy() *KeycloakClientSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClientStatus) DeepCopyInto(out *KeycloakClientStatus) {
	*out = *in
	in.Api.DeepCopyInto(&out.Api)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClientStatus.
func (in *KeycloakClientStatus) DeepCopy() *KeycloakClientStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClusterEndpoint) DeepCopyInto(out *KeycloakClusterEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClusterEndpoint.
func (in *KeycloakClusterEndpoint) DeepCopy() *KeycloakClusterEndpoint {
	if in == nil {
		return nil
	}
	out := new(KeycloakClusterEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakClusterEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakClusterEndpointList) DeepCopyInto(out *KeycloakClusterEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakClusterEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakClusterEndpointList.
func (in *KeycloakClusterEndpointList) DeepCopy() *KeycloakClusterEndpointList {
	if in == nil {
		return nil
	}
	out := new(KeycloakClusterEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakClusterEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakEndpoint) DeepCopyInto(out *KeycloakEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakEndpoint.
func (in *KeycloakEndpoint) DeepCopy() *KeycloakEndpoint {
	if in == nil {
		return nil
	}
	out := new(KeycloakEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakEndpointList) DeepCopyInto(out *KeycloakEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakEndpointList.
func (in *KeycloakEndpointList) DeepCopy() *KeycloakEndpointList {
	if in == nil {
		return nil
	}
	out := new(KeycloakEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakEndpointSpec) DeepCopyInto(out *KeycloakEndpointSpec) {
	*out = *in
	if in.CaConfigMap != nil {
		in, out := &in.CaConfigMap, &out.CaConfigMap
		*out = new(ConfigMapValue)
		**out = **in
	}
	out.BasicAuthSecret = in.BasicAuthSecret
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]Rule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakEndpointSpec.
func (in *KeycloakEndpointSpec) DeepCopy() *KeycloakEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakEndpointStatus) DeepCopyInto(out *KeycloakEndpointStatus) {
	*out = *in
	if in.LastSuccess != nil {
		in, out := &in.LastSuccess, &out.LastSuccess
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakEndpointStatus.
func (in *KeycloakEndpointStatus) DeepCopy() *KeycloakEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakLDAPFederation) DeepCopyInto(out *KeycloakLDAPFederation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakLDAPFederation.
func (in *KeycloakLDAPFederation) DeepCopy() *KeycloakLDAPFederation {
	if in == nil {
		return nil
	}
	out := new(KeycloakLDAPFederation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakLDAPFederation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakLDAPFederationList) DeepCopyInto(out *KeycloakLDAPFederationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakLDAPFederation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakLDAPFederationList.
func (in *KeycloakLDAPFederationList) DeepCopy() *KeycloakLDAPFederationList {
	if in == nil {
		return nil
	}
	out := new(KeycloakLDAPFederationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakLDAPFederationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakLDAPFederationSpec) DeepCopyInto(out *KeycloakLDAPFederationSpec) {
	*out = *in
	out.Endpoint = in.Endpoint
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(LdapFederation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakLDAPFederationSpec.
func (in *KeycloakLDAPFederationSpec) DeepCopy() *KeycloakLDAPFederationSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakLDAPFederationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakLDAPFederationStatus) DeepCopyInto(out *KeycloakLDAPFederationStatus) {
	*out = *in
	if in.Result != nil {
		in, out := &in.Result, &out.Result
		*out = new(gocloak.LDAPSyncResult)
		**out = **in
	}
	in.Api.DeepCopyInto(&out.Api)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakLDAPFederationStatus.
func (in *KeycloakLDAPFederationStatus) DeepCopy() *KeycloakLDAPFederationStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakLDAPFederationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakLDAPMapper) DeepCopyInto(out *KeycloakLDAPMapper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakLDAPMapper.
func (in *KeycloakLDAPMapper) DeepCopy() *KeycloakLDAPMapper {
	if in == nil {
		return nil
	}
	out := new(KeycloakLDAPMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakLDAPMapper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakLDAPMapperList) DeepCopyInto(out *KeycloakLDAPMapperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakLDAPMapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakLDAPMapperList.
func (in *KeycloakLDAPMapperList) DeepCopy() *KeycloakLDAPMapperList {
	if in == nil {
		return nil
	}
	out := new(KeycloakLDAPMapperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakLDAPMapperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakLDAPMapperSpec) DeepCopyInto(out *KeycloakLDAPMapperSpec) {
	*out = *in
	out.Endpoint = in.Endpoint
	if in.GroupLdapMapper != nil {
		in, out := &in.GroupLdapMapper, &out.GroupLdapMapper
		*out = new(GroupLdapMapper)
		(*in).DeepCopyInto(*out)
	}
	if in.UserAttributeLdapMapper != nil {
		in, out := &in.UserAttributeLdapMapper, &out.UserAttributeLdapMapper
		*out = new(UserAttributeLdapMapper)
		**out = **in
	}
	if in.RoleLdapMapper != nil {
		in, out := &in.RoleLdapMapper, &out.RoleLdapMapper
		*out = new(RoleLdapMapper)
		(*in).DeepCopyInto(*out)
	}
	if in.FullNameLdapMapper != nil {
		in, out := &in.FullNameLdapMapper, &out.FullNameLdapMapper
		*out = new(FullNameLdapMapper)
		**out = **in
	}
	if in.CertificateLdapMapper != nil {
		in, out := &in.CertificateLdapMapper, &out.CertificateLdapMapper
		*out = new(CertificateLdapMapper)
		**out = **in
	}
	if in.HardcodedLdapGroupMapper != nil {
		in, out := &in.HardcodedLdapGroupMapper, &out.HardcodedLdapGroupMapper
		*out = new(HardcodedLdapGroupMapper)
		**out = **in
	}
	if in.HardcodedLdapAttributeMapper != nil {
		in, out := &in.HardcodedLdapAttributeMapper, &out.HardcodedLdapAttributeMapper
		*out = new(HardcodedLdapAttributeMapper)
		**out = **in
	}
	if in.HardcodedAttributeMapper != nil {
		in, out := &in.HardcodedAttributeMapper, &out.HardcodedAttributeMapper
		*out = new(HardcodedAttributeMapper)
		**out = **in
	}
	if in.HardcodedLdapRoleMapper != nil {
		in, out := &in.HardcodedLdapRoleMapper, &out.HardcodedLdapRoleMapper
		*out = new(HardcodedLdapRoleMapper)
		**out = **in
	}
	if in.MSADUserAccountControlMapper != nil {
		in, out := &in.MSADUserAccountControlMapper, &out.MSADUserAccountControlMapper
		*out = new(MSADUserAccountControlMapper)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakLDAPMapperSpec.
func (in *KeycloakLDAPMapperSpec) DeepCopy() *KeycloakLDAPMapperSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakLDAPMapperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakLDAPMapperStatus) DeepCopyInto(out *KeycloakLDAPMapperStatus) {
	*out = *in
	if in.Result != nil {
		in, out := &in.Result, &out.Result
		*out = new(gocloak.LDAPSyncResult)
		**out = **in
	}
	in.Api.DeepCopyInto(&out.Api)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakLDAPMapperStatus.
func (in *KeycloakLDAPMapperStatus) DeepCopy() *KeycloakLDAPMapperStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakLDAPMapperStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRealm) DeepCopyInto(out *KeycloakRealm) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRealm.
func (in *KeycloakRealm) DeepCopy() *KeycloakRealm {
	if in == nil {
		return nil
	}
	out := new(KeycloakRealm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakRealm) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRealmList) DeepCopyInto(out *KeycloakRealmList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakRealm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRealmList.
func (in *KeycloakRealmList) DeepCopy() *KeycloakRealmList {
	if in == nil {
		return nil
	}
	out := new(KeycloakRealmList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakRealmList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRealmRole) DeepCopyInto(out *KeycloakRealmRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRealmRole.
func (in *KeycloakRealmRole) DeepCopy() *KeycloakRealmRole {
	if in == nil {
		return nil
	}
	out := new(KeycloakRealmRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakRealmRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRealmRoleList) DeepCopyInto(out *KeycloakRealmRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakRealmRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRealmRoleList.
func (in *KeycloakRealmRoleList) DeepCopy() *KeycloakRealmRoleList {
	if in == nil {
		return nil
	}
	out := new(KeycloakRealmRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakRealmRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRealmRoleSpec) DeepCopyInto(out *KeycloakRealmRoleSpec) {
	*out = *in
	out.Endpoint = in.Endpoint
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRealmRoleSpec.
func (in *KeycloakRealmRoleSpec) DeepCopy() *KeycloakRealmRoleSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakRealmRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRealmRoleStatus) DeepCopyInto(out *KeycloakRealmRoleStatus) {
	*out = *in
	in.Api.DeepCopyInto(&out.Api)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRealmRoleStatus.
func (in *KeycloakRealmRoleStatus) DeepCopy() *KeycloakRealmRoleStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakRealmRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRealmSpec) DeepCopyInto(out *KeycloakRealmSpec) {
	*out = *in
	out.Endpoint = in.Endpoint
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRealmSpec.
func (in *KeycloakRealmSpec) DeepCopy() *KeycloakRealmSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakRealmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRealmStatus) DeepCopyInto(out *KeycloakRealmStatus) {
	*out = *in
	in.Api.DeepCopyInto(&out.Api)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRealmStatus.
func (in *KeycloakRealmStatus) DeepCopy() *KeycloakRealmStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakRealmStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapFederation) DeepCopyInto(out *LdapFederation) {
	*out = *in
	if in.ChangedSyncPeriod != nil {
		in, out := &in.ChangedSyncPeriod, &out.ChangedSyncPeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ConnectionPooling != nil {
		in, out := &in.ConnectionPooling, &out.ConnectionPooling
		*out = new(bool)
		**out = **in
	}
	if in.ConnectionTimeout != nil {
		in, out := &in.ConnectionTimeout, &out.ConnectionTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.FullSyncPeriod != nil {
		in, out := &in.FullSyncPeriod, &out.FullSyncPeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.UserObjectClasses != nil {
		in, out := &in.UserObjectClasses, &out.UserObjectClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapFederation.
func (in *LdapFederation) DeepCopy() *LdapFederation {
	if in == nil {
		return nil
	}
	out := new(LdapFederation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MSADUserAccountControlMapper) DeepCopyInto(out *MSADUserAccountControlMapper) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MSADUserAccountControlMapper.
func (in *MSADUserAccountControlMapper) DeepCopy() *MSADUserAccountControlMapper {
	if in == nil {
		return nil
	}
	out := new(MSADUserAccountControlMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleLdapMapper) DeepCopyInto(out *RoleLdapMapper) {
	*out = *in
	if in.RoleObjectClasses != nil {
		in, out := &in.RoleObjectClasses, &out.RoleObjectClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleLdapMapper.
func (in *RoleLdapMapper) DeepCopy() *RoleLdapMapper {
	if in == nil {
		return nil
	}
	out := new(RoleLdapMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rule) DeepCopyInto(out *Rule) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Realms != nil {
		in, out := &in.Realms, &out.Realms
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rule.
func (in *Rule) DeepCopy() *Rule {
	if in == nil {
		return nil
	}
	out := new(Rule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretGenerator) DeepCopyInto(out *SecretGenerator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretGenerator.
func (in *SecretGenerator) DeepCopy() *SecretGenerator {
	if in == nil {
		return nil
	}
	out := new(SecretGenerator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subject) DeepCopyInto(out *Subject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subject.
func (in *Subject) DeepCopy() *Subject {
	if in == nil {
		return nil
	}
	out := new(Subject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserAttributeLdapMapper) DeepCopyInto(out *UserAttributeLdapMapper) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserAttributeLdapMapper.
func (in *UserAttributeLdapMapper) DeepCopy() *UserAttributeLdapMapper {
	if in == nil {
		return nil
	}
	out := new(UserAttributeLdapMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserRepresentation) DeepCopyInto(out *UserRepresentation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserRepresentation.
func (in *UserRepresentation) DeepCopy() *UserRepresentation {
	if in == nil {
		return nil
	}
	out := new(UserRepresentation)
	in.DeepCopyInto(out)
	return out
}
